# -*- coding: utf-8 -*-
"""covid_pneumonia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13r71ST_6ypeHn-WYPjltk2Vhzwhw_3ZR
"""

from fastai.vision import *
from fastai.metrics import error_rate, accuracy

from google.colab import drive
#drive.flush_and_unmount()
drive.mount('/content/gdrive', force_remount=True)
root_dir = "/content/gdrive/My Drive/"
base_dir = root_dir + 'Colab Notebooks/'

path = Path(base_dir + 'covid')
#dest = path/folder
#dest.mkdir(parents=True, exist_ok=True)

print(os.listdir(r'/content/gdrive/My Drive/Colab Notebooks/'))

path.ls()

fnames = get_image_files(path)

print(len(fnames))
pat = r'/([a-z]+)_\d+.JPG$'
np.random.seed(2)

data = ImageDataBunch.from_name_re(path, fnames, pat = pat, ds_tfms = get_transforms(), bs = 32, size = 224).normalize(imagenet_stats)

data.show_batch(3, figsize = (7, 9))

learn = cnn_learner(data, models.resnet34, metrics = accuracy)

learn.fit_one_cycle(7)

learn.save('stage-1')

interp = ClassificationInterpretation.from_learner(learn)
interp.plot_top_losses(9, figsize=(13, 15))

interp.plot_confusion_matrix()

interp.most_confused(2)

learn.unfreeze()

learn.fit_one_cycle(1)

learn.load('stage-1')

learn.lr_find()

learn.recorder.plot()

learn.unfreeze()
learn.fit_one_cycle(2, max_lr=slice(1e-5,1e-3))

interp2 = ClassificationInterpretation.from_learner(learn)
interp2.plot_confusion_matrix()

data2 = ImageDataBunch.from_name_re(path, fnames, pat = pat, ds_tfms = get_transforms(), bs = 32, size = 299).normalize(imagenet_stats)

learn2 = cnn_learner(data, models.resnet50, metrics = accuracy)

learn2.fit_one_cycle(10)

